version: "3.8"

services:
  
  database:
    image: postgres
    container_name: database_csis
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=csis
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres

volumes:
    pgdata:
        driver: local