version: '3'

services:
  csis-database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
    container_name: csis-database
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresqk/data
